apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - image: wordpress:5.1-apache
          name: wordpress
          # Load all environment variables from wordpress-php-config (configmap.yaml)
          envFrom:
          - configMapRef:
              name: env-vars
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
            # save wordpress-upload.ini --> /usr/local/etc/php/conf.custom/
            - name: php-ini
              mountPath: /usr/local/etc/php/conf.custom
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wordpress-volumeclaim
        - name: env-vars
          configMap:
            name: env-vars
        - name: php-ini
          configMap:
            name: config-files
            items:
            - key: wordpress-upload.ini
              path: wordpress-upload.ini